### ISSUE TITLE
File Streaming TODO

### ISSUE THREAD

**Issue by pcauchy1** [paradimdata/project_chameleon#23]
# TODO: make this able to stream the result and not read the entire file into memory before returning.

From line 377 in api.py. How do we want to go about streaming things so they aren't read into memory? Do you have a specific method you would like me to use, or just whatever works?

**Comment by tmcqueen-materials** [comment]
@pcauchy1 : I don't know. Because any simple approach I can come up with always has the JSON entirely in memory, at least temporarily, so is not an improvement over this. 

A non simple/elegant approach that would achieve this (instead of lines 379-380) is (in pseudocode):
```
   use subprocess.run to use the command base64 -w0 to produce a base64 encoded version of the output file without line breaks
   insert at the beginning of the file (without reading the whole file!) the part of the JSON before the base64 content, i.e. `{ 'status': 'ok', 'message': 'Files processed successfully', 'file_data':`
   insert at the end of the file (without reading the whole file!) the part of the JSON after the base64 content, i.e. `, 'file_name': os.path.basename(output_file) }`
   use FileResponse to do a streaming return of that file and then clean it up.
```
I could also imagine doing something similar by implementing your own class that implements the file operations needed by FileResponse, but processes and returns things piecewise as the caller requests a given number of bytes.
